#!/usr/bin/python
import githooks.pre_commit_directory.ansiblelint as ansiblelint
import githooks.pre_commit_directory.markdownlint as markdownlint
import githooks.pre_commit_directory.yamllint as yamllint


def main():
    has_errors = False
    ansible_output = ansiblelint.get_ansible_output()
    if len(ansible_output.results) > 0:
        has_errors = True
    print(ansible_output)
    markdown_output = markdownlint.get_markdown_output()
    if len(markdown_output.results) > 0:
        has_errors = True
    print(markdown_output)
    yamllint_output = yamllint.get_yamllint_output()
    if len(yamllint_output.results) > 0:
        has_errors = True
    print(yamllint_output)

    if has_errors:
        print("You must fix your lint errors before you can commit your files.")
        return 1
    else:
        return 0


if __name__ == '__main__':
    exit(main())
